[package]
name = "kerla"
version = "0.0.1"
authors = ["Seiya Nuta <nuta@seiya.me>"]
edition = "2018"

[[bin]]
name = "kerla"
path = "main.rs"

[dependencies]
kerla_utils = { path = "../utils", features = ["no_std"] }
spin = "0.7.1"
x86 = "0.36.0"
memoffset = "0.6.2"
buddy_system_allocator = "0.7.0"
arrayvec = { version = "0.7.0", default-features = false }
goblin = { version = "0.3", default-features = false, features = ["elf64"] }
bitflags = "1.2.1"
hashbrown = { version = "0.1.0", features = ["nightly"] }
log = "0.4"
crossbeam = { version = "0.8.0", default-features = false, features = ["alloc"] }
smoltcp = { version = "0.7.1", default-features = false, features = ["alloc", "proto-ipv4", "socket", "socket-raw", "socket-udp", "socket-tcp", "proto-dhcpv4", "ethernet"] }
