#!/bin/node
const { Supervisor } = require('.')

const supervisor = new Supervisor({
  appDir: '/app',
  adapter: {
    name: process.env['MAKESTACK_NETWORK_ADAPTER'],
    url: process.env['MAKESTACK_SERVER_URL']
  },
  mode: process.env['MAKESTACK_MODE'],
  osVersion: process.env['MAKESTACK_OS_VERSION'],
  deviceType: process.env['MAKESTACK_DEVICE_TYPE'],
  deviceId: process.env['MAKESTACK_DEVICE_ID'],
  deviceSecret: process.env['MAKESTACK_DEVICE_SECRET'],
  appUID: parseInt(process.env['MAKESTACK_APP_UID']) || undefined,
  appGID: parseInt(process.env['MAKESTACK_APP_GID']) || undefined,
  heartbeatInterval: process.env['MAKESTACK_HEARTBEAT_INTERVAL']
})

supervisor.start()
