name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        include:
          - arch: riscv64
            machine: qemu
    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        run: |
          rustup override set nightly
          rustup component add llvm-tools-preview rust-src

      - name: Build OS
        run: make build ARCH="${{ matrix.arch }}" MACHINE="${{ matrix.machine }}"
