name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Docker
        run: docker ps

      - name: Set up Rust
        run: |
          rustup override set nightly
          rustup component add llvm-tools-preview rust-src

      - name: Install cargo crates
        run: cargo install cargo-binutils rustfilt

      - name: Build the OS
        run: make RELEASE=1
