[package]
name = "noa"
version = "0.0.0"
authors = ["Seiya Nuta <nuta@seiya.me>"]
edition = "2018"

[[bin]]
name = "noa"
path = "main.rs"

[dev-dependencies]
pretty_assertions = "0"

[dependencies]
log = "0"
once_cell = "1"
anyhow = "1"
structopt = "0"
tokio = { version = "1", features = ["full"] }
futures = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
parking_lot = "0"
arrayvec = "0"
ignore = "0"
sublime_fuzzy = "0"
git2 = { version = "0", default-features = false }
libgit2-sys = "0"
phf = { version = "0", features = ["macros"] }

noa_common = { path = "../common" }
noa_cui = { path = "../cui" }
noa_buffer = { path = "../buffer" }
noa_editorconfig = { path = "../editorconfig" }
noa_langs = { path = "../langs" }
