//! Wayland Protocol definitions.

//
//
//              GENERATED BY OUR WAYLAND-SCANNER. DO NOT EDIT!
//
//

pub mod wl_buffer;
pub mod wl_callback;
pub mod wl_compositor;
pub mod wl_data_device;
pub mod wl_data_device_manager;
pub mod wl_data_offer;
pub mod wl_data_source;
pub mod wl_display;
pub mod wl_keyboard;
pub mod wl_output;
pub mod wl_pointer;
pub mod wl_region;
pub mod wl_registry;
pub mod wl_seat;
pub mod wl_shell;
pub mod wl_shell_surface;
pub mod wl_shm;
pub mod wl_shm_pool;
pub mod wl_subcompositor;
pub mod wl_subsurface;
pub mod wl_surface;
pub mod wl_touch;
pub mod xdg_popup;
pub mod xdg_positioner;
pub mod xdg_surface;
pub mod xdg_toplevel;
pub mod xdg_wm_base;

#[derive(Debug)]
pub enum EventSet {
    WlBuffer(wl_buffer::WlBuffer, wl_buffer::Event),
    WlCallback(wl_callback::WlCallback, wl_callback::Event),
    WlCompositor(wl_compositor::WlCompositor, wl_compositor::Event),
    WlDataDevice(wl_data_device::WlDataDevice, wl_data_device::Event),
    WlDataDeviceManager(
        wl_data_device_manager::WlDataDeviceManager,
        wl_data_device_manager::Event,
    ),
    WlDataOffer(wl_data_offer::WlDataOffer, wl_data_offer::Event),
    WlDataSource(wl_data_source::WlDataSource, wl_data_source::Event),
    WlDisplay(wl_display::WlDisplay, wl_display::Event),
    WlKeyboard(wl_keyboard::WlKeyboard, wl_keyboard::Event),
    WlOutput(wl_output::WlOutput, wl_output::Event),
    WlPointer(wl_pointer::WlPointer, wl_pointer::Event),
    WlRegion(wl_region::WlRegion, wl_region::Event),
    WlRegistry(wl_registry::WlRegistry, wl_registry::Event),
    WlSeat(wl_seat::WlSeat, wl_seat::Event),
    WlShell(wl_shell::WlShell, wl_shell::Event),
    WlShellSurface(wl_shell_surface::WlShellSurface, wl_shell_surface::Event),
    WlShm(wl_shm::WlShm, wl_shm::Event),
    WlShmPool(wl_shm_pool::WlShmPool, wl_shm_pool::Event),
    WlSubcompositor(wl_subcompositor::WlSubcompositor, wl_subcompositor::Event),
    WlSubsurface(wl_subsurface::WlSubsurface, wl_subsurface::Event),
    WlSurface(wl_surface::WlSurface, wl_surface::Event),
    WlTouch(wl_touch::WlTouch, wl_touch::Event),
    XdgPopup(xdg_popup::XdgPopup, xdg_popup::Event),
    XdgPositioner(xdg_positioner::XdgPositioner, xdg_positioner::Event),
    XdgSurface(xdg_surface::XdgSurface, xdg_surface::Event),
    XdgToplevel(xdg_toplevel::XdgToplevel, xdg_toplevel::Event),
    XdgWmBase(xdg_wm_base::XdgWmBase, xdg_wm_base::Event),
}

#[derive(Debug)]
pub enum RequestSet {
    WlBuffer(wl_buffer::Request),
    WlCallback(wl_callback::Request),
    WlCompositor(wl_compositor::Request),
    WlDataDevice(wl_data_device::Request),
    WlDataDeviceManager(wl_data_device_manager::Request),
    WlDataOffer(wl_data_offer::Request),
    WlDataSource(wl_data_source::Request),
    WlDisplay(wl_display::Request),
    WlKeyboard(wl_keyboard::Request),
    WlOutput(wl_output::Request),
    WlPointer(wl_pointer::Request),
    WlRegion(wl_region::Request),
    WlRegistry(wl_registry::Request),
    WlSeat(wl_seat::Request),
    WlShell(wl_shell::Request),
    WlShellSurface(wl_shell_surface::Request),
    WlShm(wl_shm::Request),
    WlShmPool(wl_shm_pool::Request),
    WlSubcompositor(wl_subcompositor::Request),
    WlSubsurface(wl_subsurface::Request),
    WlSurface(wl_surface::Request),
    WlTouch(wl_touch::Request),
    XdgPopup(xdg_popup::Request),
    XdgPositioner(xdg_positioner::Request),
    XdgSurface(xdg_surface::Request),
    XdgToplevel(xdg_toplevel::Request),
    XdgWmBase(xdg_wm_base::Request),
}
