musl_objs = \
    vendor/musl/src/ctype/__ctype_b_loc.o \
    vendor/musl/src/ctype/__ctype_get_mb_cur_max.o \
    vendor/musl/src/ctype/__ctype_tolower_loc.o \
    vendor/musl/src/ctype/__ctype_toupper_loc.o \
    vendor/musl/src/ctype/isalnum.o \
    vendor/musl/src/ctype/isalpha.o \
    vendor/musl/src/ctype/isascii.o \
    vendor/musl/src/ctype/isblank.o \
    vendor/musl/src/ctype/iscntrl.o \
    vendor/musl/src/ctype/isdigit.o \
    vendor/musl/src/ctype/isgraph.o \
    vendor/musl/src/ctype/islower.o \
    vendor/musl/src/ctype/isprint.o \
    vendor/musl/src/ctype/ispunct.o \
    vendor/musl/src/ctype/isspace.o \
    vendor/musl/src/ctype/isupper.o \
    vendor/musl/src/ctype/iswalnum.o \
    vendor/musl/src/ctype/iswalpha.o \
    vendor/musl/src/ctype/iswblank.o \
    vendor/musl/src/ctype/iswcntrl.o \
    vendor/musl/src/ctype/iswctype.o \
    vendor/musl/src/ctype/iswdigit.o \
    vendor/musl/src/ctype/iswgraph.o \
    vendor/musl/src/ctype/iswlower.o \
    vendor/musl/src/ctype/iswprint.o \
    vendor/musl/src/ctype/iswpunct.o \
    vendor/musl/src/ctype/iswspace.o \
    vendor/musl/src/ctype/iswupper.o \
    vendor/musl/src/ctype/iswxdigit.o \
    vendor/musl/src/ctype/isxdigit.o \
    vendor/musl/src/ctype/toascii.o \
    vendor/musl/src/ctype/tolower.o \
    vendor/musl/src/ctype/toupper.o \
    vendor/musl/src/ctype/towctrans.o \
    vendor/musl/src/ctype/wcswidth.o \
    vendor/musl/src/ctype/wctrans.o \
    vendor/musl/src/ctype/wcwidth.o \
    vendor/musl/src/errno/strerror.o \
    vendor/musl/src/internal/floatscan.o \
    vendor/musl/src/internal/intscan.o \
    vendor/musl/src/internal/libc.o \
    vendor/musl/src/internal/shgetc.o \
    vendor/musl/src/locale/c_locale.o \
    vendor/musl/src/locale/__lctrans.o \
    vendor/musl/src/locale/catclose.o \
    vendor/musl/src/locale/catgets.o \
    vendor/musl/src/locale/catopen.o \
    vendor/musl/src/locale/duplocale.o \
    vendor/musl/src/locale/freelocale.o \
    vendor/musl/src/locale/iconv.o \
    vendor/musl/src/locale/langinfo.o \
    vendor/musl/src/locale/localeconv.o \
    vendor/musl/src/locale/newlocale.o \
    vendor/musl/src/locale/strcoll.o \
    vendor/musl/src/locale/strfmon.o \
    vendor/musl/src/locale/strxfrm.o \
    vendor/musl/src/locale/uselocale.o \
    vendor/musl/src/locale/wcscoll.o \
    vendor/musl/src/locale/wcsxfrm.o \
    vendor/musl/src/math/__cos.o \
    vendor/musl/src/math/__cosdf.o \
    vendor/musl/src/math/__cosl.o \
    vendor/musl/src/math/__expo2.o \
    vendor/musl/src/math/__expo2f.o \
    vendor/musl/src/math/__fpclassify.o \
    vendor/musl/src/math/__fpclassifyf.o \
    vendor/musl/src/math/__fpclassifyl.o \
    vendor/musl/src/math/__invtrigl.o \
    vendor/musl/src/math/__polevll.o \
    vendor/musl/src/math/__rem_pio2.o \
    vendor/musl/src/math/__rem_pio2_large.o \
    vendor/musl/src/math/__rem_pio2f.o \
    vendor/musl/src/math/__rem_pio2l.o \
    vendor/musl/src/math/__signbit.o \
    vendor/musl/src/math/__signbitf.o \
    vendor/musl/src/math/__signbitl.o \
    vendor/musl/src/math/__sin.o \
    vendor/musl/src/math/__sindf.o \
    vendor/musl/src/math/__sinl.o \
    vendor/musl/src/math/__tan.o \
    vendor/musl/src/math/__tandf.o \
    vendor/musl/src/math/__tanl.o \
    vendor/musl/src/math/acos.o \
    vendor/musl/src/math/acosf.o \
    vendor/musl/src/math/acosh.o \
    vendor/musl/src/math/acoshf.o \
    vendor/musl/src/math/acoshl.o \
    vendor/musl/src/math/acosl.o \
    vendor/musl/src/math/asin.o \
    vendor/musl/src/math/asinf.o \
    vendor/musl/src/math/asinh.o \
    vendor/musl/src/math/asinhf.o \
    vendor/musl/src/math/asinhl.o \
    vendor/musl/src/math/asinl.o \
    vendor/musl/src/math/atan.o \
    vendor/musl/src/math/atan2.o \
    vendor/musl/src/math/atan2f.o \
    vendor/musl/src/math/atan2l.o \
    vendor/musl/src/math/atanf.o \
    vendor/musl/src/math/atanh.o \
    vendor/musl/src/math/atanhf.o \
    vendor/musl/src/math/atanhl.o \
    vendor/musl/src/math/atanl.o \
    vendor/musl/src/math/cbrt.o \
    vendor/musl/src/math/cbrtf.o \
    vendor/musl/src/math/cbrtl.o \
    vendor/musl/src/math/ceil.o \
    vendor/musl/src/math/ceilf.o \
    vendor/musl/src/math/ceill.o \
    vendor/musl/src/math/copysign.o \
    vendor/musl/src/math/copysignf.o \
    vendor/musl/src/math/copysignl.o \
    vendor/musl/src/math/cos.o \
    vendor/musl/src/math/cosf.o \
    vendor/musl/src/math/cosh.o \
    vendor/musl/src/math/coshf.o \
    vendor/musl/src/math/coshl.o \
    vendor/musl/src/math/cosl.o \
    vendor/musl/src/math/erf.o \
    vendor/musl/src/math/erff.o \
    vendor/musl/src/math/erfl.o \
    vendor/musl/src/math/exp.o \
    vendor/musl/src/math/exp10.o \
    vendor/musl/src/math/exp10f.o \
    vendor/musl/src/math/exp10l.o \
    vendor/musl/src/math/exp2.o \
    vendor/musl/src/math/exp2f.o \
    vendor/musl/src/math/exp2l.o \
    vendor/musl/src/math/expf.o \
    vendor/musl/src/math/expl.o \
    vendor/musl/src/math/expm1.o \
    vendor/musl/src/math/expm1f.o \
    vendor/musl/src/math/expm1l.o \
    vendor/musl/src/math/fabs.o \
    vendor/musl/src/math/fabsf.o \
    vendor/musl/src/math/fabsl.o \
    vendor/musl/src/math/fdim.o \
    vendor/musl/src/math/fdimf.o \
    vendor/musl/src/math/fdiml.o \
    vendor/musl/src/math/floor.o \
    vendor/musl/src/math/floorf.o \
    vendor/musl/src/math/floorl.o \
    vendor/musl/src/math/fma.o \
    vendor/musl/src/math/fmaf.o \
    vendor/musl/src/math/fmal.o \
    vendor/musl/src/math/fmax.o \
    vendor/musl/src/math/fmaxf.o \
    vendor/musl/src/math/fmaxl.o \
    vendor/musl/src/math/fmin.o \
    vendor/musl/src/math/fminf.o \
    vendor/musl/src/math/fminl.o \
    vendor/musl/src/math/fmod.o \
    vendor/musl/src/math/fmodf.o \
    vendor/musl/src/math/fmodl.o \
    vendor/musl/src/math/frexp.o \
    vendor/musl/src/math/frexpf.o \
    vendor/musl/src/math/frexpl.o \
    vendor/musl/src/math/hypot.o \
    vendor/musl/src/math/hypotf.o \
    vendor/musl/src/math/hypotl.o \
    vendor/musl/src/math/ilogb.o \
    vendor/musl/src/math/ilogbf.o \
    vendor/musl/src/math/ilogbl.o \
    vendor/musl/src/math/j0.o \
    vendor/musl/src/math/j0f.o \
    vendor/musl/src/math/j1.o \
    vendor/musl/src/math/j1f.o \
    vendor/musl/src/math/jn.o \
    vendor/musl/src/math/jnf.o \
    vendor/musl/src/math/ldexp.o \
    vendor/musl/src/math/ldexpf.o \
    vendor/musl/src/math/ldexpl.o \
    vendor/musl/src/math/lgamma.o \
    vendor/musl/src/math/lgamma_r.o \
    vendor/musl/src/math/lgammaf.o \
    vendor/musl/src/math/lgammaf_r.o \
    vendor/musl/src/math/lgammal.o \
    vendor/musl/src/math/llrint.o \
    vendor/musl/src/math/llrintf.o \
    vendor/musl/src/math/llrintl.o \
    vendor/musl/src/math/llround.o \
    vendor/musl/src/math/llroundf.o \
    vendor/musl/src/math/llroundl.o \
    vendor/musl/src/math/log.o \
    vendor/musl/src/math/log10.o \
    vendor/musl/src/math/log10f.o \
    vendor/musl/src/math/log10l.o \
    vendor/musl/src/math/log1p.o \
    vendor/musl/src/math/log1pf.o \
    vendor/musl/src/math/log1pl.o \
    vendor/musl/src/math/log2.o \
    vendor/musl/src/math/log2f.o \
    vendor/musl/src/math/log2l.o \
    vendor/musl/src/math/logb.o \
    vendor/musl/src/math/logbf.o \
    vendor/musl/src/math/logbl.o \
    vendor/musl/src/math/logf.o \
    vendor/musl/src/math/logl.o \
    vendor/musl/src/math/lrint.o \
    vendor/musl/src/math/lrintf.o \
    vendor/musl/src/math/lrintl.o \
    vendor/musl/src/math/lround.o \
    vendor/musl/src/math/lroundf.o \
    vendor/musl/src/math/lroundl.o \
    vendor/musl/src/math/modf.o \
    vendor/musl/src/math/modff.o \
    vendor/musl/src/math/modfl.o \
    vendor/musl/src/math/nan.o \
    vendor/musl/src/math/nanf.o \
    vendor/musl/src/math/nanl.o \
    vendor/musl/src/math/nearbyint.o \
    vendor/musl/src/math/nearbyintf.o \
    vendor/musl/src/math/nearbyintl.o \
    vendor/musl/src/math/nextafter.o \
    vendor/musl/src/math/nextafterf.o \
    vendor/musl/src/math/nextafterl.o \
    vendor/musl/src/math/nexttoward.o \
    vendor/musl/src/math/nexttowardf.o \
    vendor/musl/src/math/nexttowardl.o \
    vendor/musl/src/math/pow.o \
    vendor/musl/src/math/powf.o \
    vendor/musl/src/math/powl.o \
    vendor/musl/src/math/remainder.o \
    vendor/musl/src/math/remainderf.o \
    vendor/musl/src/math/remainderl.o \
    vendor/musl/src/math/remquo.o \
    vendor/musl/src/math/remquof.o \
    vendor/musl/src/math/remquol.o \
    vendor/musl/src/math/rint.o \
    vendor/musl/src/math/rintf.o \
    vendor/musl/src/math/rintl.o \
    vendor/musl/src/math/round.o \
    vendor/musl/src/math/roundf.o \
    vendor/musl/src/math/roundl.o \
    vendor/musl/src/math/scalb.o \
    vendor/musl/src/math/scalbf.o \
    vendor/musl/src/math/scalbln.o \
    vendor/musl/src/math/scalblnf.o \
    vendor/musl/src/math/scalblnl.o \
    vendor/musl/src/math/scalbn.o \
    vendor/musl/src/math/scalbnf.o \
    vendor/musl/src/math/scalbnl.o \
    vendor/musl/src/math/signgam.o \
    vendor/musl/src/math/significand.o \
    vendor/musl/src/math/significandf.o \
    vendor/musl/src/math/sin.o \
    vendor/musl/src/math/sincos.o \
    vendor/musl/src/math/sincosf.o \
    vendor/musl/src/math/sincosl.o \
    vendor/musl/src/math/sinf.o \
    vendor/musl/src/math/sinh.o \
    vendor/musl/src/math/sinhf.o \
    vendor/musl/src/math/sinhl.o \
    vendor/musl/src/math/sinl.o \
    vendor/musl/src/math/sqrt.o \
    vendor/musl/src/math/sqrtf.o \
    vendor/musl/src/math/sqrtl.o \
    vendor/musl/src/math/tan.o \
    vendor/musl/src/math/tanf.o \
    vendor/musl/src/math/tanh.o \
    vendor/musl/src/math/tanhf.o \
    vendor/musl/src/math/tanhl.o \
    vendor/musl/src/math/tanl.o \
    vendor/musl/src/math/tgamma.o \
    vendor/musl/src/math/tgammaf.o \
    vendor/musl/src/math/tgammal.o \
    vendor/musl/src/math/trunc.o \
    vendor/musl/src/math/truncf.o \
    vendor/musl/src/math/truncl.o \
    vendor/musl/src/fenv/fenv.o \
    vendor/musl/src/multibyte/btowc.o \
    vendor/musl/src/multibyte/internal.o \
    vendor/musl/src/multibyte/mblen.o \
    vendor/musl/src/multibyte/mbrlen.o \
    vendor/musl/src/multibyte/mbrtowc.o \
    vendor/musl/src/multibyte/mbsinit.o \
    vendor/musl/src/multibyte/mbsnrtowcs.o \
    vendor/musl/src/multibyte/mbsrtowcs.o \
    vendor/musl/src/multibyte/mbstowcs.o \
    vendor/musl/src/multibyte/mbtowc.o \
    vendor/musl/src/multibyte/wcrtomb.o \
    vendor/musl/src/multibyte/wcsnrtombs.o \
    vendor/musl/src/multibyte/wcsrtombs.o \
    vendor/musl/src/multibyte/wcstombs.o \
    vendor/musl/src/multibyte/wctob.o \
    vendor/musl/src/multibyte/wctomb.o \
    vendor/musl/src/stdlib/abs.o \
    vendor/musl/src/stdlib/atof.o \
    vendor/musl/src/stdlib/atoi.o \
    vendor/musl/src/stdlib/atol.o \
    vendor/musl/src/stdlib/atoll.o \
    vendor/musl/src/stdlib/bsearch.o \
    vendor/musl/src/stdlib/div.o \
    vendor/musl/src/stdlib/ecvt.o \
    vendor/musl/src/stdlib/fcvt.o \
    vendor/musl/src/stdlib/gcvt.o \
    vendor/musl/src/stdlib/imaxabs.o \
    vendor/musl/src/stdlib/imaxdiv.o \
    vendor/musl/src/stdlib/labs.o \
    vendor/musl/src/stdlib/ldiv.o \
    vendor/musl/src/stdlib/llabs.o \
    vendor/musl/src/stdlib/lldiv.o \
    vendor/musl/src/stdlib/qsort.o \
    vendor/musl/src/stdlib/strtod.o \
    vendor/musl/src/stdlib/strtol.o \
    vendor/musl/src/stdlib/wcstod.o \
    vendor/musl/src/stdlib/wcstol.o \
    vendor/musl/src/string/bcmp.o \
    vendor/musl/src/string/bcopy.o \
    vendor/musl/src/string/bzero.o \
    vendor/musl/src/string/index.o \
    vendor/musl/src/string/memccpy.o \
    vendor/musl/src/string/memchr.o \
    vendor/musl/src/string/memcmp.o \
    vendor/musl/src/string/memcpy.o \
    vendor/musl/src/string/memmem.o \
    vendor/musl/src/string/memmove.o \
    vendor/musl/src/string/mempcpy.o \
    vendor/musl/src/string/memrchr.o \
    vendor/musl/src/string/memset.o \
    vendor/musl/src/string/rindex.o \
    vendor/musl/src/string/stpcpy.o \
    vendor/musl/src/string/stpncpy.o \
    vendor/musl/src/string/strcasecmp.o \
    vendor/musl/src/string/strcasestr.o \
    vendor/musl/src/string/strcat.o \
    vendor/musl/src/string/strchr.o \
    vendor/musl/src/string/strchrnul.o \
    vendor/musl/src/string/strcmp.o \
    vendor/musl/src/string/strcpy.o \
    vendor/musl/src/string/strcspn.o \
    vendor/musl/src/string/strdup.o \
    vendor/musl/src/string/strerror_r.o \
    vendor/musl/src/string/strlcat.o \
    vendor/musl/src/string/strlcpy.o \
    vendor/musl/src/string/strlen.o \
    vendor/musl/src/string/strncasecmp.o \
    vendor/musl/src/string/strncat.o \
    vendor/musl/src/string/strncmp.o \
    vendor/musl/src/string/strncpy.o \
    vendor/musl/src/string/strndup.o \
    vendor/musl/src/string/strnlen.o \
    vendor/musl/src/string/strpbrk.o \
    vendor/musl/src/string/strrchr.o \
    vendor/musl/src/string/strsep.o \
    vendor/musl/src/string/strsignal.o \
    vendor/musl/src/string/strspn.o \
    vendor/musl/src/string/strstr.o \
    vendor/musl/src/string/strtok.o \
    vendor/musl/src/string/strtok_r.o \
    vendor/musl/src/string/strverscmp.o \
    vendor/musl/src/string/swab.o \
    vendor/musl/src/string/wcpcpy.o \
    vendor/musl/src/string/wcpncpy.o \
    vendor/musl/src/string/wcscasecmp.o \
    vendor/musl/src/string/wcscasecmp_l.o \
    vendor/musl/src/string/wcscat.o \
    vendor/musl/src/string/wcschr.o \
    vendor/musl/src/string/wcscmp.o \
    vendor/musl/src/string/wcscpy.o \
    vendor/musl/src/string/wcscspn.o \
    vendor/musl/src/string/wcsdup.o \
    vendor/musl/src/string/wcslen.o \
    vendor/musl/src/string/wcsncasecmp.o \
    vendor/musl/src/string/wcsncasecmp_l.o \
    vendor/musl/src/string/wcsncat.o \
    vendor/musl/src/string/wcsncmp.o \
    vendor/musl/src/string/wcsncpy.o \
    vendor/musl/src/string/wcsnlen.o \
    vendor/musl/src/string/wcspbrk.o \
    vendor/musl/src/string/wcsrchr.o \
    vendor/musl/src/string/wcsspn.o \
    vendor/musl/src/string/wcsstr.o \
    vendor/musl/src/string/wcstok.o \
    vendor/musl/src/string/wcswcs.o \
    vendor/musl/src/string/wmemchr.o \
    vendor/musl/src/string/wmemcmp.o \
    vendor/musl/src/string/wmemcpy.o \
    vendor/musl/src/string/wmemmove.o \
    vendor/musl/src/string/wmemset.o \
    vendor/musl/src/malloc/memalign.o \
    vendor/musl/src/malloc/posix_memalign.o

objs += $(musl_objs)
