#!/bin/sh
set -ue
ARCH=$1

if [ "$ARCH" = "host" ]; then
  yarn node-gyp rebuild
  ARCH=$(node -e "console.log(process.arch)")
else
  yarn node-gyp rebuild --arch $ARCH
fi

mkdir -p native/$ARCH
mv build/Release/*.node native/$ARCH
