#!/usr/bin/env python3
import glob


def main():
    files = 0
    lines = 0
    exts = ['c', 'h', 'py']
    for ext in exts:
        for f in glob.iglob('**/*.' + ext, recursive=True):
            with open(f) as f:
                lines += len(f.readlines())
            files += 1

    print("{} files and {} lines total".format(files, lines))

if __name__ == "__main__":
    main()
