#!/usr/bin/env python3
#
#  Installs build tools and generates a Makefile variables.
#
import argparse
import os
import platform
import sys
import subprocess


def main():
    f = open(sys.argv[1], "w")
    packages = os.environ.get("PACKAGES", "").split()
    os_name = platform.system().lower()

    if os_name == "darwin":
        fomulae = ["llvm", "binutils", "python", "wget", "qemu", "git"]
        subprocess.run(["brew", "install"] + fomulae)

        f.write("""\
LLVM_DIR = /usr/local/opt/llvm
CC  = $(LLVM_DIR)/bin/clang   --target=x86_64-linux-elf
CXX = $(LLVM_DIR)/bin/clang++ --target=x86_64-linux-elf
LD  = $(LLVM_DIR)/bin/ld.lld
OBJCOPY = gobjcopy
""".format(**locals()))
    elif os_name == "linux":
        f.write("""\
CC  = gcc
CXX = g++
LD  = ld
OBJCOPY = objcopy
""".format(**locals()))
    else:
        sys.exit("Unsupported operating system.")

    version = subprocess.check_output(["git", "rev-parse", "HEAD"]) \
                        .decode("utf-8").strip()

    f.write('''\
VERSION = {version}
CMDECHO = printf "  \\033[1;34m%7s  \\033[0;33m%s\\033[m\\n"
PYTHON  = python3
'''.format(**locals()))

if __name__ == "__main__":
    main()
