#!/usr/bin/env python3
import argparse
from resea.helpers import render

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('build_dir')
    parser.add_argument('template')
    parser.add_argument('output')
    args = parser.parse_args()

    with open(args.output, 'w') as f:
        f.write(render(open(args.template).read(), {
            'BUILD_DIR': args.build_dir
        }))

if __name__ == '__main__':
    main()
