#!/bin/sh
set -e

cp -r $X86_DIR/isofiles $BUILD_DIR
cp $1 $BUILD_DIR/isofiles/boot/executable

# many grep(1) are for suppressing messages we do not care
grub-mkrescue -o $2 $BUILD_DIR/isofiles 2>&1 | \
    grep -v 'RockRidge filesystem manipulator' | \
    grep -v '^Drive current' | \
    grep -v '^Media current' | \
    grep -v '^Media status' | \
    grep -v '^Media summary' | \
    grep -v '^Added to ISO image' | \
    grep -v '^ISO image produced' | \
    grep -v '^Written to medium' | \
    grep -v "^Writing to '.*' completed successfully" | \
    grep -v '^xorriso.*UPDATE.*files added' | \
    grep -v '^xorriso.*UPDATE.*Thank you for being patient' | \
    grep -v '^xorriso.*NOTE.*Copying to System Area' | \
    grep -v "share/locale': No such file or directory" | \
    grep -v '^$'
