#!/bin/sh
exec qemu-system-x86_64 \
    -m 256 -localtime -nographic \
    -no-reboot -boot d \
    -cpu SandyBridge \
    -net user -net nic,model=virtio \
    -net dump,file=qemu.pcap \
    -cdrom $1
