language: rust
rust: nightly
dist: xenial
sudo: false
os:
  - linux
  - osx

env:
  - RUST_BACKTRACE=1

# Install clang, lld, and Python3.7 from PPA on Ubuntu 16.04 build.
addons:
  homebrew:
    packages:
      - binutils
      - llvm
  apt:
    sources:
      - deadsnakes
      - llvm-toolchain-xenial-8
    packages:
      - python3.7
      - python3.7-venv
      - python3.7-dev
      - lld-8
      - clang-8

cache:
  cargo: true

notifications:
  email: false

install:
  - ./tools/ci/setup

script:
  - ./tools/ci/script
