#!/bin/node
const Supervisor = require('.')

const url = process.env['MAKESTACK_SERVER_URL']
const deviceId = process.env['MAKESTACK_DEVICE_ID']

console.log('*** starting supervisor');
(new Supervisor(url, deviceId)).start()
