source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.1.3'
gem 'puma', '~> 3.7'
gem 'jbuilder'
gem 'devise'
gem 'devise_token_auth'
gem 'jbuilder'
gem 'sidekiq'
gem 'pg', group: :postgres
gem 'redis-objects'
gem 'redis-namespace'
gem 'msgpack'
gem 'rest-client'
gem 'strong_migrations'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'sqlite3'
  gem 'pry-rails'
  gem 'active_record_query_trace'
  gem 'ffaker'
  gem 'factory_girl_rails'
  gem 'foreman'
  gem 'jekyll', require: false
  gem 'guard-rspec', require: false
end

group :test do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rspec-rails'
  gem 'rspec-json_expectations'
  gem 'database_cleaner'
  gem 'simplecov', require: false
  gem 'simplecov-json', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
