#!/bin/sh
ROOT=$(git rev-parse --show-toplevel)
cd $ROOT

cd runtime
yarn
cd ..

cd supervisor
yarn
cd ..

cd sdk
yarn
cd ..

cd supervisor
rm -rf node_modules/makestack
ln -s $ROOT/runtime node_modules/makestack
cd ..

cd sdk
rm -rf node_modules/makestack
rm -rf node_modules/@makestack/supervisor
ln -s $ROOT/runtime node_modules/makestack
ln -s $ROOT/supervisor node_modules/@makestack/supervisor
cd ..

