# ESP-IDF build config.
COMPONENT_SRCDIRS = .. ../../..
CXXFLAGS += -fdiagnostics-color=always

ifneq ($(MAKESTACK_APP),)
CXXFLAGS += -DMAKESTACK_APP
endif

ifneq ($(MAKESTACK_HEARTBEAT_INTERVAL),)
CXXFLAGS += -DMAKESTACK_HEARTBEAT_INTERVAL=$(MAKESTACK_HEARTBEAT_INTERVAL)
endif
