#!/bin/busybox sh

# First, install symbolic links to /busybox into /bin and /sbin.
/bin/busybox mkdir -p /sbin /bin
/bin/busybox --install -s


cd /
mkdir -p sys proc tmp
mount -t sysfs    sysfs    /sys
mount -t securityfs securityfs /sys/kernel/security
mount -t proc     proc     /proc
mount -t devtmpfs devtmpfs /dev

cat <<"EOF"
 __  __       _        ____  _             _       _     _                  
|  \/  | __ _| | _____/ ___|| |_ __ _  ___| | __  | |   (_)_ __  _   ___  __
| |\/| |/ _` | |/ / _ \___ \| __/ _` |/ __| |/ /  | |   | | '_ \| | | \ \/ /
| |  | | (_| |   <  __/___) | || (_| | (__|   <   | |___| | | | | |_| |>  < 
|_|  |_|\__,_|_|\_\___|____/ \__\__,_|\___|_|\_\  |_____|_|_| |_|\__,_/_/\_\

EOF

for interface in $(echo /sys/class/net/* | xargs -n1 basename); do
    [ "$interface" = "lo" ] && continue
    
    ip link set $interface up
    udhcpc -i $interface -s /etc/udhcpc.script
done

root=$(egrep -o "root=([^ ]+)" /proc/cmdline | awk -F= '{print $2}')
[ "$root" = "" ] || echo "Error: root is not speicifed in /proc/cmdline" > /dev/stderr
mkdir /disk
mount $root /disk

. /disk/config.sh
hostname makestack-linux
cat /etc/apparmor.policy > /sys/kernel/security/apparmor/.replace

echo "Boot time: $(awk '{print $1}' /proc/uptime) secs"

if [ "$DEBUG" = "" ]; then
    node app/main.js
else
    node bin/test-userland.js
    poweroff -f
fi

echo "*** something went wrong, rebooting..."
reboot -f
sleep 180
