#!/bin/busybox sh

# First, install symbolic links to /busybox into /bin and /sbin.
/bin/busybox mkdir -p /sbin /bin
/bin/busybox --install -s


cd /
mkdir -p dev sys proc tmp
mount -t sysfs    sysfs    /sys
mount -t proc     proc     /proc
mount -t devtmpfs devtmpfs /dev

cat <<"EOF"
 __  __       _        ____  _             _       _     _                  
|  \/  | __ _| | _____/ ___|| |_ __ _  ___| | __  | |   (_)_ __  _   ___  __
| |\/| |/ _` | |/ / _ \___ \| __/ _` |/ __| |/ /  | |   | | '_ \| | | \ \/ /
| |  | | (_| |   <  __/___) | || (_| | (__|   <   | |___| | | | | |_| |>  < 
|_|  |_|\__,_|_|\_\___|____/ \__\__,_|\___|_|\_\  |_____|_|_| |_|\__,_/_/\_\

EOF

hostname makestack-linux

for interface in $(echo /sys/class/net/* | xargs -n1 basename); do
    [ "$interface" = "lo" ] && continue
    
    ip link set $interface up
    udhcpc -i $interface -s /etc/udhcpc.script
done

echo "Boot time: $(awk '{print $1}' /proc/uptime) secs"

grep debug /proc/cmdline > /dev/null && /bin/test-userland.js

echo "BUG: Something wrong with init, dropping to shell..."
exec /bin/busybox sh
