#!/bin/bash
set -ue
ESP_IDF_VERSION=391c3ff959f9eb1b2975cb0d7b29c0478f3b6a48
ARDUINO_ESP32_VERSION=25dff4f044151f7f766c64b9d2ad90398472e6b3
JERRYSCRIPT_VERSION=79289714dced3121c703cba4bde7bbfa2f78c934

if [[ -f deps/README ]]; then
    echo "Dependencies are already downloaded, exiting..."
    exit 0
fi

rm -rf deps deps.tmp
mkdir deps.tmp
pushd deps.tmp
if [[ "$(uname)" == "Darwin" ]]; then
    toolchain_url=https://dl.espressif.com/dl/xtensa-esp32-elf-osx-1.22.0-80-g6c4433a-5.2.0.tar.gz
else
    toolchain_url=https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-61-gab8375a-5.2.0.tar.gz
fi

curl -fSL $toolchain_url | tar zxf -

git clone https://github.com/espressif/esp-idf
pushd esp-idf
git checkout $ESP_IDF_VERSION
git submodule update --init --recursive
popd

git clone --recursive https://github.com/espressif/arduino-esp32
pushd arduino-esp32
git checkout $ARDUINO_ESP32_VERSION
git submodule update --init --recursive
popd

git clone https://github.com/jerryscript-project/jerryscript
pushd jerryscript
git checkout $JERRYSCRIPT_VERSION
popd

echo "dependencies" > README
popd

mv deps.tmp deps

pushd plugins
yarn
popd
