#!/bin/bash
if [ "$(uname)" = "Darwin" ]; then
    brew install coreutils gnu-tar python3 llvm binutils \
        qemu bochs mtools cquery
elif [ "$TRAVIS" = "true" ]; then
    pyenv global 3.6.3
    wget http://www.antlr.org/download/antlr-4.7.1-complete.jar
else
    sudo apt install build-essential clang mtools qemu-system \
        python3 python3-pip
fi

pip3 install antlr4-python3-runtime
