#!/bin/sh
set -ue
[ "$1" = "" ] && echo "Usage: $0 version" && exit 1

VERSION=$1
DIST_DIR=$(realpath dist)

mkdir -p $DIST_DIR

echo "==> Packaging SDK..."
pushd sdk
npm pack
mv makestack-*.tgz $DIST_DIR/makestack-sdk-$VERSION.tar.gz
popd

echo "==> Packaging installer..."
pushd sdk/installer
yarn build:macos
yarn build:linux

pushd builds/makestack-installer-darwin-x64
zip -r $DIST_DIR/makestack-installer-$VERSION-macos.zip makestack-installer.app
popd

pushd builds
tar Jcf $DIST_DIR/makestack-installer-$VERSION-linux-x64.tar.xz makestack-installer-linux-x64
popd

popd

echo "==> Packaging Plugins..."
for plugin in runtime plugins/*; do
  ./sdk/bin/makestack build-plugin $plugin $DIST_DIR/$(basename $plugin)-$VERSION.plugin.zip
echo
done

echo "==> Building linux..."
cd linux
make prepare
for target in raspberrypi3; do
  make TARGET=$target BUILD=release DOCKER=1
  mv build/$target/makestack-linux-$target.img $DIST_DIR/makestack-linux-$VERSION-$target.img
  rm -rf $DIST_DIR/linux
done
