#!/usr/bin/env python3
import argparse
import sys
import os
import resea


APPS_C_FMT = """\
#include <resea.h>

{% for app in apps %}
void {{ app }}_startup(void);
{% endfor %}

uintptr_t apps[] = {
{% for app in apps %}
    (uintptr_t) {{ app }}_startup,
{% endfor %}
    (uintptr_t) NULL
};
"""


def main(args):
    print(resea.fmt(APPS_C_FMT, {
        "apps": list(map(lambda app: resea.to_package_id(app), args.apps))
    }))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="A apps.c generator")
    parser.add_argument("apps", nargs="+", help="Application names.")
    main(parser.parse_args())
