#!/bin/sh
ROOT=$PWD

cd runtime
yarn
cd ..

cd supervisor
yarn
cd ..

cd sdk
yarn
cd ..

cd supervisor
rm -rf node_modules/@makestack/runtime
ln -s $ROOT/runtime node_modules/@makestack/runtime
cd ..

cd sdk
rm -rf node_modules/@makestack/runtime
rm -rf node_modules/@makestack/supervisor
ln -s $ROOT/runtime node_modules/@makestack/runtime
ln -s $ROOT/supervisor node_modules/@makestack/supervisor
cd ..

