#!/usr/bin/env node
const fs = require('fs')
const path = require('path')
const dts = require('dts-bundle')
const { spawnSync } = require('child_process')

const pluginDirs = fs
  .readdirSync(path.resolve(__dirname, '../../../plugins'))
  .map(name => path.join(__dirname, '../../../plugins', name))
  .filter(dir => fs.existsSync(path.join(dir, 'package.json')))

const dirs = [
  path.resolve(__dirname, '../../../runtime'),
  ...pluginDirs
]

const dtsJson = []
const tmpFilePath = '/tmp/tmp.d.ts'

for (const dir of dirs) {
  const name = JSON.parse(fs.readFileSync(
    path.join(dir, 'package.json'))
  ).name

  spawnSync('yarn', ['prepack'], { stdio: 'inherit', cwd: dir })

  dts.bundle({
    name,
    main: `${dir}/dist`,
    out: tmpFilePath
  })

  dtsJson.push({
    name,
    body: fs.readFileSync(tmpFilePath, { encoding: 'utf-8' })
  })
}

fs.writeFileSync(
  path.resolve(__dirname, '../assets/dts.json'),
  JSON.stringify(dtsJson, null, 2)
)

console.log('generated assets/dts.json')
