#!/usr/bin/env python3
import argparse
import sys


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('header', default='')
    parser.add_argument('footer', default='')
    args = parser.parse_args()

    print(args.header)
    for i, b in enumerate(sys.stdin.buffer.read()):
        if i % 100 == 0:
            print('')
        print(hex(b) + ',', end='')
    print(args.footer)

if __name__ == '__main__':
    main()
